- id: '1605436785972'
  alias: 'Door: Turn on bathroom lights when door opens'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_door_sensor
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.bathroom_lights
  mode: single
- id: '1605438904093'
  alias: 'Door: Run arriving script when front door opens'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.front_door_sensor
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.motion_detected_in_last_5_minutes
    state: 'off'
  action:
  - service: script.arriving
    data: {}
  mode: single
