background: var(--background-image)
title: Home
views:
  - theme: dark-mode
    badges:
      - entity: person.liam
    path: home
    icon: mdi:home
    cards:
      - type: vertical-stack
        cards:
          - entities:
              - entities:
                  - entity: light.tv_ambilight
                    icon: mdi:television
                  - light.corner_lamp
                  - light.table_lamp
                  - light.java_lamp
                  - light.standing_lamp
                  - entity: scene.living_room_chill
                    name: "Set scene to: Chill"
                    icon: mdi:script-outline
                type: custom:fold-entity-row
                head:
                  color_picker: true
                  entity: light.living_room_lights
                  name: Living
                  type: custom:slider-entity-row
                  icon: mdi:sofa
              - entities:
                  - light.bedroom_ceiling
                  - light.bedside_lamp
                type: custom:fold-entity-row
                head:
                  entity: light.bedroom
                  icon: mdi:bed-double
                  type: custom:slider-entity-row
                  name: Bedroom
              - entities:
                  - light.bathroom_mirror
                  - light.bathroom_toilet
                  - light.bathroom_shower
                type: custom:fold-entity-row
                head:
                  entity: light.bathroom
                  name: Bathroom
                  icon: mdi:shower
                  type: custom:slider-entity-row
              - entities:
                  - light.hallway_entrance
                  - light.hallway_spot
                type: custom:fold-entity-row
                head:
                  entity: light.hallway
                  name: Hallway
                  icon: mdi:hanger
                  type: custom:slider-entity-row
            show_header_toggle: false
            title: Lights
            type: entities
          - type: thermostat
            entity: climate.living_room
      - type: vertical-stack
        cards:
          - type: iframe
            aspect_ratio: 400x100
            url: "https://g6-cgm.herokuapp.com/clock/clock-color"
          - type: "custom:mini-graph-card"
            animate: true
            color_thresholds:
              - color: "#039BE5"
                value: 2
              - color: "#0DA035"
                value: 5
              - color: "#E0B400"
                value: 10
              - color: "#E45E65"
                value: 15
            detail: 2
            entities:
              - entity: sensor.dexcom_liamwoodleigh_glucose_value
                show_fill: true
                show_state: false
                smoothing: true
            hours_to_show: 12
            line_width: 3
            name: CGM Graph - 12 Hours
            points_per_hour: 60
            show:
              graph: line
              labels: true
            unit: mmol/L
          - type: media-control
            entity: media_player.spotify_liam_woodleigh
      - type: vertical-stack
        cards:
          - type: weather-forecast
            entity: weather.home
          - type: entities
            title: Garbage
            entities:
              - entity: sensor.mijnafvalwijzer_restafval
                name: Restafval
                icon: "hass:delete-empty"
              - entity: sensor.mijnafvalwijzer_papier
                name: Papier
                icon: "hass:file"
      - type: vertical-stack
        cards:
          - entities:
              - entity: vacuum.xiaomi_vacuum_cleaner
                name: Vacuum cleaner
                primary:
                  entity: binary_sensor.vacuum_day
                  name: Vacuum day
                secondary:
                  attribute: battery_level
                  name: Battery
                  unit: "%"
                type: custom:multiple-entity-row
              - entity: switch.vacuum_mode
              - entity: input_boolean.cleaned_today
              - entity: binary_sensor.vacuum_day
            show_header_toggle: false
            type: entities
            title: Vacuum
