background: var(--background-image)
title: Home
decluttering_templates:
  automation_template:
    card:
      card:
        show_header_toggle: false
        title: "[[name]] automations"
        type: entities
      filter:
        include:
          - entity_id: automation.[[slug]]*
      sort: entity_id
      type: custom:auto-entities

views:
  - theme: dark-mode
    title: home
    badges:
      - entity: person.liam
    path: home
    icon: mdi:home
    cards:
      - type: vertical-stack
        cards:
          - entities:
              - entities:
                  - entity: light.tv_ambilight
                    icon: mdi:television
                  - light.corner_lamp
                  - light.table_lamp
                  - light.java_lamp
                  - light.standing_lamp
                  - entity: scene.living_room_chill
                    name: "Scene: Chill"
                    icon: mdi:script-outline
                type: custom:fold-entity-row
                head:
                  color_picker: true
                  entity: light.living_room_lights
                  name: Living
                  type: custom:slider-entity-row
                  icon: mdi:sofa
              - entities:
                  - light.bedroom_ceiling
                  - light.bedside_lamp
                type: custom:fold-entity-row
                head:
                  entity: light.bedroom
                  icon: mdi:bed-double
                  type: custom:slider-entity-row
                  name: Bedroom
              - entities:
                  - light.hallway_entrance
                  - light.hallway_spot
                  - light.cabinet_left
                  - light.cabinet_middle
                  - light.cabinet_right
                  - entity: scene.bathroom_nightlight
                    name: "Scene: Nightlight"
                    icon: mdi:script-outline
                type: custom:fold-entity-row
                head:
                  entity: light.hallway
                  name: Hallway
                  icon: mdi:hanger
                  type: custom:slider-entity-row
              - entities:
                  - light.bathroom_mirror
                  - light.bathroom_toilet
                  - light.bathroom_shower
                  - entity: scene.bathroom_energize
                    name: "Scene: Energize"
                    icon: mdi:script-outline
                type: custom:fold-entity-row
                head:
                  entity: light.bathroom
                  name: Bathroom
                  icon: mdi:shower
                  type: custom:slider-entity-row
            show_header_toggle: false
            title: Lights
            type: entities
          - type: custom:simple-thermostat
            entity: climate.living_room
            step_layout: row
            name: false
            icon: false
            control: true
            decimals: 1
      - type: vertical-stack
        cards:
          - type: custom:mini-media-player
            artwork: cover
            background: /local/tv1.jpg
            entity: media_player.tv
            hide:
              controls: true
              mute: false
              play_stop: true
              volume: true
            icon: mdi:television
          - type: custom:mini-media-player
            artwork: cover
            entity: media_player.spotify
            hide:
              power: true
              source: false
              volume: true
            icon: mdi:spotify
          - type: weather-forecast
            entity: weather.home
          - type: custom:swipe-card
            parameters:
            spaceBetween: 8
            scrollbar:
              hide: false
              draggable: true
              snapOnRelease: true
            cards:
              - name: CGM Graph - 12 Hours
                animate: true
                color_thresholds:
                  - color: "#039BE5"
                    value: 2
                  - color: "#0DA035"
                    value: 5
                  - color: "#E0B400"
                    value: 10
                  - color: "#E45E65"
                    value: 15
                detail: 2
                entities:
                  - entity: sensor.dexcom_liamwoodleigh_glucose_value
                    show_fill: true
                    show_state: false
                    smoothing: true
                hours_to_show: 12
                line_width: 3
                points_per_hour: 60
                show:
                  graph: line
                  labels: true
                type: "custom:mini-graph-card"
                unit: mmol/L
              - type: entities
                title: Garbage
                entities:
                  - entity: sensor.mijnafvalwijzer_restafval
                    name: Restafval
                    icon: "hass:delete-empty"
                  - entity: sensor.mijnafvalwijzer_papier
                    name: Papier
                    icon: "hass:file"
              - aggregate_func: avg
                animate: true
                color_thresholds:
                  - color: "#039BE5"
                    value: 2
                  - color: "#0da035"
                    value: 5
                  - color: "#e0b400"
                    value: 10
                  - color: "#e45e65"
                    value: 15
                entities:
                  - entity: sensor.dexcom_liamwoodleigh_glucose_value
                group_by: date
                hours_to_show: 168
                name: Avg CGM Value Per Day
                show:
                  graph: bar
                  labels: true
                  state: true
                type: "custom:mini-graph-card"
      - type: vertical-stack
        cards:
          - type: custom:xiaomi-vacuum-card
            entity: vacuum.xiaomi_vacuum_cleaner
            name: Vacuum
          - entities:
              - entity: input_boolean.cleaned_today
              - entity: binary_sensor.vacuum_day
            show_header_toggle: false
            type: entities
          - type: custom:xiaomi-vacuum-map-card
            map_camera: camera.xiaomi_cloud_map_extractor
            camera_calibration: true
            entity: vacuum.xiaomi_vacuum_cleaner
  - title: CGM
    badges: []
    icon: mdi:chart-bell-curve
    path: CGM
    cards:
      - cards:
          - color_thresholds:
              - color: "#039BE5"
                value: 2
              - color: "#0DA035"
                value: 5
              - color: "#E0B400"
                value: 10
              - color: "#E45E65"
                value: 15
            detail: 1
            entities:
              - entity: sensor.liams_hba1c_value
                show_fill: false
                show_state: true
                smoothing: true
            hours_to_show: 2160
            icon: "mdi:water"
            line_width: 3
            name: HbA1C Avg - 90 days
            show:
              graph: line
            type: "custom:mini-graph-card"
            unit: "%"
          - color_thresholds:
              - color: "#039BE5"
                value: 2
              - color: "#0DA035"
                value: 5
              - color: "#E0B400"
                value: 10
              - color: "#E45E65"
                value: 15
            detail: 1
            entities:
              - entity: sensor.glucose_avg_90d
                show_fill: false
                show_state: true
                smoothing: true
            hours_to_show: 2160
            icon: "mdi:water"
            line_width: 3
            name: Estimated Avg Glucose - 90 days
            show:
              graph: line
            type: "custom:mini-graph-card"
            unit: mmol/L
          - aggregate_func: avg
            animate: true
            color_thresholds:
              - color: "#039BE5"
                value: 2
              - color: "#0da035"
                value: 5
              - color: "#e0b400"
                value: 10
              - color: "#e45e65"
                value: 15
            entities:
              - entity: sensor.dexcom_liamwoodleigh_glucose_value
            group_by: date
            hours_to_show: 168
            name: Avg CGM Value Per Day
            show:
              graph: bar
              labels: true
              state: true
            type: "custom:mini-graph-card"
        type: vertical-stack
      - cards:
          - aspect_ratio: 500x220
            type: iframe
            url: "https://g6-cgm.herokuapp.com/clock/clock-color"
        type: vertical-stack
      - cards:
          - animate: true
            color_thresholds:
              - color: "#039BE5"
                value: 2
              - color: "#0DA035"
                value: 5
              - color: "#E0B400"
                value: 10
              - color: "#E45E65"
                value: 15
            detail: 2
            entities:
              - entity: sensor.dexcom_liamwoodleigh_glucose_value
                show_fill: true
                show_state: false
                smoothing: true
            hours_to_show: 12
            line_width: 3
            name: CGM Graph - 12 Hours
            points_per_hour: 60
            show:
              graph: line
              labels: true
            type: "custom:mini-graph-card"
            unit: mmol/L
          - animate: true
            color_thresholds:
              - color: "#c0392b"
                value: 3
              - color: "#08ff2d"
                value: 5
              - color: "#f7ff08"
                value: 10
              - color: "#ff3508"
                value: 15
            detail: 1
            entities:
              - sensor.dexcom_liamwoodleigh_glucose_value
            graph: line
            hours_to_show: 36
            line_width: 3
            name: CGM Graph - 36 Hours
            points_per_hour: 30
            show:
              labels: true
            type: "custom:mini-graph-card"
          - animate: true
            color_thresholds:
              - color: "#c0392b"
                value: 3
              - color: "#08ff2d"
                value: 5
              - color: "#f7ff08"
                value: 10
              - color: "#ff3508"
                value: 15
            entities:
              - sensor.dexcom_liamwoodleigh_glucose_value
            hours_to_show: 168
            line_width: 3
            name: CGM Graph - 7 Days
            points_per_hour: 5
            show:
              labels: true
              state: true
            type: "custom:mini-graph-card"
          - cards: []
            type: horizontal-stack
        type: vertical-stack
  - icon: mdi:robot
    path: automations
    title: Automations
    badges: []
    cards:
      - card:
          show_header_toggle: false
          title: Uncategorized automations
          type: entities
        filter:
          exclude:
            - entity_id: automation.alarm_clock_*
            - entity_id: automation.apple_watch*
            - entity_id: automation.arriving_*
            - entity_id: automation.climate_*
            - entity_id: automation.bg_*
            - entity_id: automation.frontend_*
            - entity_id: automation.leaving_*
            - entity_id: automation.light_*
            - entity_id: automation.lights_*
            - entity_id: automation.lovelace_*
            - entity_id: automation.media_player_*
            - entity_id: automation.plant_*
            - entity_id: automation.system_*
            - entity_id: automation.utilities_*
            - entity_id: automation.vacuum_*
          include:
            - domain: automation
        sort: entity_id
        type: custom:auto-entities
      - template: automation_template
        type: custom:decluttering-card
        variables:
          - name: Arriving
          - slug: arriving_
      - template: automation_template
        type: custom:decluttering-card
        variables:
          - name: Climate
          - slug: climate
      - template: automation_template
        type: custom:decluttering-card
        variables:
          - name: Leaving
          - slug: leaving
      - template: automation_template
        type: custom:decluttering-card
        variables:
          - name: BG
          - slug: bg
      - template: automation_template
        type: custom:decluttering-card
        variables:
          - name: Light
          - slug: light
      - template: automation_template
        type: custom:decluttering-card
        variables:
          - name: Plant
          - slug: plant
      - template: automation_template
        type: custom:decluttering-card
        variables:
          - name: Vacuum
          - slug: vacuum
      - template: automation_template
        type: custom:decluttering-card
        variables:
          - name: Apple Watch
          - slug: apple_watch
