- alias: "Light: turn off dining room (extra check)"
  description: In case the other automation failed
  trigger:
    platform: time_pattern
    minutes: "/30"
  condition:
    - condition: state
      entity_id: binary_sensor.activity_in_living_room
      state: "off"
    - condition: state
      entity_id: light.dining_room_lights
      state: "on"
  action:
    service: light.turn_off
    entity_id: light.dining_room_lights