- id: "motion_light_hallway"
  alias: "Light: Turn on hallway lights on motion"
  trigger:
    - platform: state
      entity_id: binary_sensor.activity_in_hallway
      to: "on"
  condition:
    - condition: state
      entity_id: light.hallway_lights
      state: "off"
    - condition: state
      entity_id: input_boolean.automatic_lights
      state: "on"
  action:
    - service: adaptive_lighting.apply
      data:
        entity_id: switch.adaptive_lighting_hallway
        lights: light.hallway_lights
        transition: 1
        turn_on_lights: true
    - wait_for_trigger:
        platform: state
        entity_id: binary_sensor.activity_in_hallway
        from: "on"
        to: "off"
    - delay: 180
    - service: light.turn_off
      target:
        entity_id: light.hallway_lights
  mode: restart

- alias: "Light: Turn on Hallway Lights when state changes from unavailable"
  description: "Sets the Hallway Lights to on when it becomes available."
  trigger:
    - platform: state
      entity_id: light.hallway_lights
      from: "unavailable"
    - platform: state
      entity_id: light.hallway_lights
      from: "unknown"
  action:
    - service: light.turn_on
      target:
        entity_id: light.hallway_lights
      data:
        brightness: 255
        color_temp_kelvin: 6500
    - service: adaptive_lighting.set_manual_control
      data:
        entity_id:
          - switch.adaptive_lighting_hallway
        manual_control: false
  mode: single

- alias: "Light: turn off staircase when hallway motion stops"
  trigger:
    platform: state
    entity_id: binary_sensor.activity_in_hallway
    from: "on"
    to: "off"
  condition:
    - condition: state
      entity_id: input_boolean.automatic_lights
      state: "on"
  action:
    service: light.turn_off
    data:
      entity_id: light.staircase_lights

- alias: "Light: Re-on hallway if motion"
  id: "motion_light_hallway_reon"
  trigger:
    - platform: state
      entity_id: light.hallway_lights
      to: "off"
  condition:
    - condition: state
      entity_id: binary_sensor.activity_in_hallway
      state: "on"
    - condition: state
      entity_id: input_boolean.automatic_lights
      state: "on"
  action:
    - service: adaptive_lighting.apply
      data:
        entity_id: switch.adaptive_lighting_hallway
        lights: light.hallway_lights
        transition: 1
        turn_on_lights: true
  mode: single
