- id: 'motion_light_hallway_with_lux'
  alias: "Light: Turn on hallway lights only when dark"
  use_blueprint:
    path: motion/motion_light_lux.yaml
    input:
      motion_entity: binary_sensor.activity_in_hallway
      light_sensor: sensor.hallway_illuminance
      illuminance_threshold: 5500
      light_target: light.hallway_lights
      no_motion_wait: 180
      adaptive_switch: switch.adaptive_lighting_hallway

- alias: "Light: Turn on Hallway Lights when state changes from unavailable"
  description: "Sets the Hallway Lights to on when it becomes available."
  trigger:
    - platform: state
      entity_id: light.hallway_lights
      from: "unavailable"
    - platform: state
      entity_id: light.hallway_lights
      from: "unknown"
  action:
    - service: light.turn_on
      target:
        entity_id: light.hallway_lights
      data:
        brightness: 255
        color_temp_kelvin: 6500
    - service: adaptive_lighting.set_manual_control
      data:
        entity_id:
          - switch.adaptive_lighting_hallway
        manual_control: false
  mode: single

- alias: "Light: turn off hallway"
  trigger:
    platform: state
    entity_id: binary_sensor.activity_in_hallway
    from: "on"
    to: "off"
  condition:
    - condition: state
      entity_id: input_boolean.automatic_lights
      state: "on"
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.hallway_lights
        - light.staircase_lights

- alias: "Light: Re-on hallway if motion and dark"
  id: "motion_light_hallway_reon_dark"
  trigger:
    - platform: state
      entity_id: light.hallway_lights
      to: "off"
  condition:
    - condition: state
      entity_id: binary_sensor.activity_in_hallway
      state: "on"
    - condition: numeric_state
      entity_id: sensor.hallway_illuminance
      attribute: light_level
      below: 5500
    - condition: state
      entity_id: input_boolean.automatic_lights
      state: "on"
  action:
    - service: adaptive_lighting.apply
      data:
        entity_id: switch.adaptive_lighting_hallway
        lights: light.hallway_lights
        transition: 1
        turn_on_lights: true
  mode: single
