- id: "motion_light_staircase_with_lux"
  alias: "Light: Turn on staircase lights only when dark"
  use_blueprint:
    path: motion/motion_light_lux.yaml
    input:
      motion_entity: binary_sensor.activity_on_staircase
      light_sensor: sensor.staircase_illuminance
      illuminance_threshold: 4500
      light_target: light.staircase_lights
      no_motion_wait: 180
      adaptive_switch: switch.adaptive_lighting_staircase
      use_adaptive: true

- alias: "Light: Turn on staircase lights when state changes from unavailable"
  use_blueprint:
    path: light_unavailable_recovery.yaml
    input:
      light_entity: light.staircase_lights
      adaptive_switch: switch.adaptive_lighting_staircase
  mode: single
