- alias: "Light: Turn on toilet light on motion"
  description: "Turns on the toilet light when motion is detected."
  trigger:
    - platform: state
      entity_id: binary_sensor.toilet_motion
      to: "on"
  condition:
    - condition: state
      entity_id: light.toilet_lights
      state: "off"
  action:
    - service: light.turn_on
      target:
        entity_id: light.toilet_lights
      data:
        brightness: 255
        color_temp_kelvin: 2700
  mode: single

- alias: "Light: Turn off toilet light on motion"
  description: "Turns off the toilet light when motion is no longer detected."
  trigger:
    - platform: state
      entity_id: binary_sensor.activity_in_toilet
      to: "off"
  condition:
    - condition: state
      entity_id: light.toilet_lights
      state: "on"
  action:
    - service: light.turn_off
      target:
        entity_id: light.toilet_lights
  mode: single

- alias: "Light: Turn on Toilet light when state changes from unavailable"
  description: "Sets the toilet light to on when it becomes available."
  trigger:
    - platform: state
      entity_id: light.toilet_lights
      from: "unavailable"
    - platform: state
      entity_id: light.toilet_lights
      from: "unknown"
  action:
    - service: light.turn_on
      target:
        entity_id: light.toilet_lights
      data:
        brightness: 255
        color_temp_kelvin: 2700
    - service: input_boolean.turn_on
      entity_id: input_boolean.toilet_activity_override
    - delay: "00:00:05"
    - service: input_boolean.turn_off
      entity_id: input_boolean.toilet_activity_override
  mode: single

- alias: "Light: Turn on Toilet light when state changes from unavailable"
  description: "Sets the toilet light to on when it becomes available."
  trigger:
    - platform: state
      entity_id: light.toilet
      from: "unavailable"
    - platform: state
      entity_id: light.toilet
      from: "unknown"
  action:
    - service: light.turn_on
      target:
        entity_id: light.toilet
      data:
        brightness: 255
        color_temp_kelvin: 2700
    - service: input_boolean.turn_on
      entity_id: input_boolean.toilet_activity_override
    - delay: "00:00:05"
    - service: input_boolean.turn_off
      entity_id: input_boolean.toilet_activity_override
  mode: single


- alias: "Light: turn off toilet (extra check)"
  description: In case the other automation failed
  trigger:
    platform: time_pattern
    minutes: "/15"
  condition:
    - condition: state
      entity_id: binary_sensor.activity_in_toilet
      state: "off"
    - condition: state
      entity_id: light.toilet_lights
      state: "on"
  action:
    service: light.turn_off
    entity_id: light.toilet_lights
