- alias: "Light: turn on upstairs lights if motion upstairs or staircase"
  trigger:
    - platform: state
      entity_id: binary_sensor.activity_upstairs
      to: "on"
    - platform: state
      entity_id: binary_sensor.activity_on_staircase
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.activity_upstairs
      state: "false"
    - condition: state
      entity_id: input_boolean.automatic_lights
      state: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.upstairs_lights
        transition: 1