---
- alias: "Arriving: switch music from iPhone to speakers"
  trigger:
    platform: state
    entity_id: binary_sensor.motion_detected
    from: "off"
    to: "on"
  condition:
    - condition: time
      before: "23:00:00"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
    - "{{ is_state_attr('media_player.spotify', 'source', 'Liam’s iPhone') }}" # And Liam's iPhone is selected as the spotify source
    - "{{ is_state('media_player.spotify', 'playing') }}" # And Spotify is playing
  action:
    - service: notify.mobile_app_liams_iphone
      data:
        title: "Arriving"
        message: "Switching music from phone to TV"
    - service: media_player.turn_on
      entity_id: media_player.tv
    - service: media_player.select_source
      entity_id: media_player.tv
      data:
        source: "\U0001F4F1 Spotify"
    - service: media_player.select_source
      entity_id: media_player.spotify
      data:
        source: Living Room TV
