---
- alias: "Arriving: switch music from iPhone to soundbar"
  description: ""
  trigger:
    platform: state
    entity_id: binary_sensor.openclose_front_door
    to: "on"
  condition:
    - condition: time
      before: "23:00:00"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: "off"
    - "{{ is_state_attr('media_player.spotify', 'source', 'Liam’s iPhone') }}" # And Liam's iPhone is selected as the spotify source
    - "{{ is_state('media_player.spotify', 'playing') }}" # And Spotify is playing
    - condition: state
      entity_id: binary_sensor.motion_detected_in_last_5_minutes
      state: "off"
  action:
    - service: script.switch_music_from_iphone_to_soundbar

- alias: "Arriving: Turn on lights and heating"
  description: ""
  trigger:
    - platform: state
      entity_id: binary_sensor.openclose_front_door
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.motion_detected_in_last_5_minutes
      state: "off"
  action:
    - service: script.arriving
      data: {}
  mode: single
