---
- alias: "Lights: Turn off bathroom after 15 minutes"
  description: ""
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_motion
      to: "off"
      for: 0:15:00
      from: "on"
  condition: []
  action:
    service: light.turn_off
    data:
      entity_id: light.bathroom_lights
  mode: single
- alias: "Lights: Turn off hallway after 1 hour"
  description: ""
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_motion
      to: "off"
      attribute: sensitivity
      from: "on"
      for: "1:00:00"
  condition: []
  action:
    service: light.turn_off
    data:
      entity_id: light.hallway_lights
  mode: single
- alias: "Lights: Turn on bathroom lights when door opens"
  description: ""
  trigger:
    - type: opened
      platform: device
      device_id: f71438264bf00faabf9df480352d3b25
      entity_id: binary_sensor.bathroom_door_sensor
      domain: binary_sensor
  condition: []
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.workday_sensor
              state: "off"
          sequence:
            - scene: scene.bathroom_energize
        - conditions:
            - condition: state
              entity_id: binary_sensor.workday_sensor
              state: "on"
            - condition: time
              after: "19:30:00"
          sequence:
            - scene: scene.bathroom_relax
        - conditions:
            - condition: state
              entity_id: binary_sensor.workday_sensor
              state: "on"
            - condition: time
              after: "22:30:00"
          sequence:
            - scene: scene.bathroom_nightlight
      default:
        - scene: scene.bathroom_energize
  mode: single
