---
- alias: "Lights: Workday Nightlight"
  description: ""
  trigger:
    - type: motion
      platform: device
      device_id: 48d7ced70bd011eba87c3ff9365e8b47
      entity_id: binary_sensor.motion_sensor_motion
      domain: binary_sensor
  condition:
    - condition: time
      after: "22:00"
      weekday:
        - mon
        - wed
        - thu
        - sun
  action:
    - scene: scene.bathroom_nightlight
  mode: single
- alias: "Lights: Morning energise"
  description: ""
  trigger:
    - type: motion
      platform: device
      device_id: 48d7ced70bd011eba87c3ff9365e8b47
      entity_id: binary_sensor.motion_sensor_motion
      domain: binary_sensor
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
      after: "6:00:00"
      before: "11:59"
    - condition: state
      entity_id: binary_sensor.no_one_home
      state: "off"
  action:
    - scene: scene.bathroom_energize
  mode: single
- alias: "Lights: Daytime"
  description: ""
  trigger:
    - platform: time
      at: "10:00:00"
    - type: motion
      platform: device
      device_id: 48d7ced70bd011eba87c3ff9365e8b47
      entity_id: binary_sensor.motion_sensor_motion
      domain: binary_sensor
  condition:
    - condition: time
      after: "10:00"
      before: "22:00"
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
    - condition: state
      entity_id: binary_sensor.no_one_home
      state: "off"
  action:
    - scene: scene.bathroom_bright
  mode: single
- alias: "Lights: Turn off bathroom after 15 minutes"
  description: ""
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_motion
      to: "off"
      for: 0:15:00
      from: "on"
  condition: []
  action:
    service: light.turn_off
    data:
      entity_id: light.bathroom_lights
  mode: single
- alias: "Lights: Turn off hallway after 1.5 hours"
  description: ""
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_motion
      to: "off"
      attribute: sensitivity
      from: "on"
      for: "1:30:00"
  condition: []
  action:
    service: light.turn_off
    data:
      entity_id: light.hallway_lights
  mode: single
