---
- alias: "Lights: Workday Nightlight"
  description: ""
  trigger:
    - type: motion
      platform: device
      device_id: 48d7ced70bd011eba87c3ff9365e8b47
      entity_id: binary_sensor.motion_sensor_motion
      domain: binary_sensor
  condition:
    - condition: time
      after: "22:00"
      weekday:
        - mon
        - wed
        - thu
        - sun
  action:
    - scene: scene.bathroom_nightlight
  mode: single
- alias: "Lights: Turn off bathroom after 15 minutes"
  description: ""
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_motion
      to: "off"
      for: 0:15:00
      from: "on"
  condition: []
  action:
    service: light.turn_off
    data:
      entity_id: light.bathroom_lights
  mode: single
- alias: "Lights: Turn off hallway after 1 hour"
  description: ""
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_motion
      to: "off"
      attribute: sensitivity
      from: "on"
      for: "1:00:00"
  condition: []
  action:
    service: light.turn_off
    data:
      entity_id: light.hallway_lights
  mode: single
- alias: "Lights: Turn on bathroom & hallway with motion"
  description: ""
  trigger:
    - type: motion
      platform: device
      device_id: 48d7ced70bd011eba87c3ff9365e8b47
      entity_id: binary_sensor.motion_sensor_motion
      domain: binary_sensor
  condition: []
  action:
    service: adaptive_lighting.apply
    data:
      entity_id:
        - switch.adaptive_lighting_hallway
        - switch.adaptive_lighting_bathroom
      lights:
        - light.hallway_lights
        - light.bathroom_lights
      turn_on_lights: true
  mode: single
