---
- alias: "Night mode: automatically turn off when alarm turns off or at 7:30AM"
  trigger:
    - platform: time
      at: "07:30"
    - platform: state
      entity_id: input_boolean.alarm_clock
      from: "on"
      to: "off"
  condition:
    condition: state
    entity_id: input_boolean.alarm_clock
    state: "off"
  action:
    entity_id: input_select.sleep_mode
    service: input_select.select_option
    data:
      option: "off"

- alias: "Night mode: set low temperature when sleep mode turns on"
  trigger:
    platform: state
    entity_id: input_select.sleep_mode
    to: "on"
  action:
    service: script.set_low_temperature

- alias: "Night mode: set high temperature when sleep mode turns off"
  trigger:
    platform: state
    entity_id: input_select.sleep_mode
    to: "off"
  action:
    service: script.set_high_temperature

- alias: "Night mode: enable on when no motion in house"
  description: "When there is no activity in the house for more than an hour enable sleep mode."
  trigger:
    platform: state
    entity_id: binary_sensor.activity_outside_bedroom
    to: "off"
    for: "01:00:00"
  condition:
    - condition: state
      entity_id: group.people
      state: home
    - condition: time
      after: "21:00:00"
  action:
    entity_id: input_select.sleep_mode
    service: input_select.select_option
    data:
      option: "on"
