---
- platform: template
  sensors:
    someone_showering:
      unique_id: someone_showering
      friendly_name: Someone is showering
      value_template: >-
        {% set humidity = states("sensor.temperature_sensor_bathroom_humidity") | float(0) %}
        {% set treshold = 1.05 * state_attr("sensor.temperature_sensor_bathroom_humidity_stats", "median") | float(0) %}
        {% set derivative = states("sensor.temperature_sensor_bathroom_humidity_derivative") | float(0) %}
        {{ humidity > treshold and derivative > 0.25 }}
      icon_template: >
        {%- if states('binary_sensor.someone_showering') == on -%}
        mdi:shower-head
        {%- else -%}
        mdi:shower
        {%- endif -%}

    motion_detected:
      unique_id: motion_detected
      friendly_name: Any motion detected
      value_template: >-
        {{ is_state("binary_sensor.activity_in_hallway", "on")
        or is_state("binary_sensor.activity_on_staircase", "on")
        or is_state("binary_sensor.activity_in_living_room", "on")
        or is_state("binary_sensor.activity_in_bathroom", "on")
        or is_state("binary_sensor.activity_in_kitchen", "on")
        or is_state("binary_sensor.activity_in_bedroom", "on")
        or is_state("binary_sensor.activity_in_toilet", "on") }}

    motion_detected_downstairs:
      unique_id: motion_detected_downstairs
      friendly_name: Any motion detected downstairs
      value_template: >-
        {{ is_state("binary_sensor.activity_in_hallway", "on")
        or is_state("binary_sensor.activity_in_living_room", "on")
        or is_state("binary_sensor.activity_in_toilet", "on")
        or is_state("binary_sensor.activity_in_kitchen", "on") }}

    motion_detected_in_last_hour:
      unique_id: motion_detected_in_last_hour
      friendly_name: Any motion detected in last hour
      value_template: >-
        {{ is_state("binary_sensor.motion_detected", "on") }}
      delay_off: "01:00:00"

    motion_detected_in_last_5_minutes:
      unique_id: motion_detected_in_last_5_minutes
      friendly_name: Any motion detected in last 5 minutes
      value_template: >-
        {{ is_state("binary_sensor.motion_detected", "on") }}
      delay_off: "00:05:00"

    someone_in_the_house_in_last_hour:
      unique_id: someone_in_the_house_in_last_hour
      friendly_name: Someone in the house in the last hour
      value_template: >-
        {{ is_state("binary_sensor.motion_detected_in_last_hour", "on")
            or is_state("group.people", "home") }}

    activity_in_hallway:
      unique_id: activity_in_hallway
      friendly_name: Activity in the hallway
      value_template: >-
        {{ is_state("binary_sensor.motion_sensor_hallway", "on")
        or is_state("binary_sensor.activity_on_staircase", "on")
        or is_state("binary_sensor.hallway_motion", "on") }}
      delay_off: "00:01:00"

    activity_on_staircase:
      unique_id: activity_on_staircase
      friendly_name: Activity on the staircase
      value_template: >-
        {{ is_state("binary_sensor.staircase_motion", "on") }}
      delay_off: "00:01:00"

    activity_in_living_space:
      unique_id: activity_in_living_space
      friendly_name: Activity in the living space
      value_template: >-
        {{ is_state("binary_sensor.activity_in_kitchen", "on")
        or is_state("binary_sensor.activity_in_living_room", "on") }}
      delay_off: "00:01:00"

    activity_in_bathroom:
      unique_id: activity_in_bathroom
      friendly_name: Activity in the bathroom
      value_template: >-
        {{ is_state("binary_sensor.motion_sensor_bathroom", "on")
            or is_state("binary_sensor.someone_showering", "on") }}
      delay_off: "00:05:00"

    activity_outside_bedroom:
      unique_id: activity_outside_bedroom
      friendly_name: Activity anywhere outside the bedroom
      value_template: >-
        {{ is_state("binary_sensor.activity_in_bathroom", "on")
          or is_state("binary_sensor.activity_on_staircase", "on")
          or is_state("binary_sensor.activity_in_hallway", "on")
          or is_state("binary_sensor.activity_in_kitchen", "on")
          or is_state("binary_sensor.activity_in_toilet", "on")
          or is_state("binary_sensor.activity_in_living_room", "on") }}
      delay_off: "00:03:00"

    activity_in_bedroom:
      unique_id: activity_in_bedroom
      friendly_name: Activity in the bedroom
      value_template: >-
        {{ is_state("binary_sensor.motion_sensor_bedroom", "on")
        or is_state("binary_sensor.bedroom_motion", "on") }}
      delay_off: "00:01:00"

    activity_in_living_room:
      unique_id: activity_in_living_room
      friendly_name: Activity in the living room
      value_template: >-
        {{ is_state("binary_sensor.living_room_motion", "on")
        or is_state("binary_sensor.entrance_motion", "on") }}
      delay_off: "00:20:00"

    activity_in_toilet:
      unique_id: activity_in_toilet
      friendly_name: "Activity in the toilet"
      value_template: >-
        {{ is_state('binary_sensor.motion_sensor_toilet', 'on')
            or is_state('binary_sensor.toilet_motion', 'on')
            or is_state('input_boolean.toilet_activity_override', 'on') }}
      delay_off: "00:01:00"

    activity_in_kitchen:
      unique_id: activity_in_kitchen
      friendly_name: Activity in the kitchen
      value_template: >-
        {{ is_state("binary_sensor.motion_sensor_kitchen", "on")
        or is_state("binary_sensor.kitchen_motion", "on") }}
      delay_off: "00:20:00"

    activity_on_ground_floor:
      unique_id: activity_on_ground_floor
      friendly_name: Activity on the ground floor
      value_template: >-
        {{ is_state("binary_sensor.activity_in_toilet", "on")
        or is_state("binary_sensor.activity_in_kitchen", "on")
        or is_state("binary_sensor.activity_in_hallway", "on")
        or is_state("binary_sensor.activity_in_living_room", "on") }}
      delay_off: "00:20:00"

    worked_enough_today:
      unique_id: worked_enough_today
      friendly_name: Worked enough today
      value_template: >-
        {{ states("sensor.time_at_work_today") | float(0) > 8 }}
      icon_template: mdi:work

    any_light_on:
      unique_id: any_light_on
      friendly_name: Any light is on
      value_template: >-
        {% set bedroom_lights_on = is_state("light.bedroom_lights", "on") %}
        {% set living_room_lights_on = is_state("light.living_room_lights", "on") %}
        {% set bathroom_lights_on = is_state("light.bathroom_lights", "on") %}
        {% set hallway_lights_on = is_state("light.hallway_lights", "on") %}
        {% set pantry_lights_on = is_state("light.pantry_lights", "on") %}
        {% set kitchen_lights_on = is_state("light.kitchen_lights", "on") %}
        {% set toilet_light_on = is_state("light.toilet", "on") %}
        {{ bathroom_lights_on or bedroom_lights_on or living_room_lights_on or hallway_lights_on or pantry_lights_on or toilet_light_on }}

    anything_on:
      unique_id: anything_on
      friendly_name: Anything is on
      value_template: >-
        {% set light_on = is_state("binary_sensor.any_light_on", "on") %}
        {% set tv_on = is_state("media_player.living_room_android_tv", "on") %}
        {% set heating_on = is_state_attr('climate.living_room', 'hvac_action', heating) %}
        {{ light_on or tv_on or heating_on}}

    no_one_home:
      unique_id: no_one_home
      friendly_name: No one is home
      value_template: >-
        {{
        not is_state("person.liam", "home")
        and not is_state("binary_sensor.ping_liams_iphone_pad", "on")
        }}

- platform: trend
  sensors:
    temperature_sensor_bathroom_humidity_trend:
      entity_id: sensor.temperature_sensor_bathroom_humidity
      sample_duration: 300
      max_samples: 3

- platform: workday
  country: NL
