---
- platform: trend
  sensors:
    temperature_sensor_bathroom_humidity_trend:
      entity_id: sensor.temperature_sensor_bathroom_humidity
      sample_duration: 300
      max_samples: 3
# - platform: workday
#   country: NL
