---
# - platform: philips_ambilight
#   name: TV Ambilight
#   host: !secret tv_ip
#   username: !secret tv_username
#   password: !secret tv_password

- platform: group
  name: All the lights
  entities:
    - light.living_room_lights
    - light.bedroom_lights
    - light.bathroom_lights
    - light.hallway_lights
    - light.kitchen_lights

- platform: group
  name: Living Room Lights
  entities:
    - light.entrance_spot_1
    - light.entrance_spot_2
    - light.entrance_spot_3
    - light.entrance_spot_4
    - light.living_room_middle_spot_1
    - light.living_room_middle_spot_2
    - light.living_room_middle_spot_3
    - light.living_room_middle_spot_4
    - light.standing_lamp

- platform: group
  name: Bedroom lights
  entities:
    - light.bedside_lamp_left
    - light.bedside_lamp_right

- platform: group
  name: Bathroom Lights
  entities:
    - light.bathroom_back
    - light.bathroom_entrance
    - light.bathroom_middle_hallway
    - light.bathroom_middle_sink

- platform: group
  name: Hallway lights
  entities:
    - light.hallway

- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_bench_upper_strip
    - light.kitchen_bench_lower_strip
    - light.kitchen_spot_1
    - light.kitchen_spot_2
    - light.kitchen_spot_3
    - light.kitchen_spot_4
    - light.table_lamp

- platform: group
  name: Pantry Lights
  entities:
    - light.pantry_spot_top
    - light.pantry_spot_middle
    - light.pantry_spot_bottom

- platform: group
  name: Toilet Lights
  entities:
    - light.toilet
