---
# - platform: philips_ambilight
#   name: TV Ambilight
#   host: !secret tv_ip
#   username: !secret tv_username
#   password: !secret tv_password

- platform: group
  name: All the lights
  entities:
    - light.top_floor_lights
    - light.first_floor_lights
    - light.ground_floor_lights

- platform: group
  name: Top Floor Lights
  entities:
    - light.office_lights
    - light.guest_room_lights
    - light.laundry_lights

- platform: group
  name: First Floor Lights
  entities:
    - light.bedroom_lights
    - light.gym_lights
    - light.walk_in_wardrobe_ceiling
    - light.bathroom_lights
    - light.staircase_first_floor_hallway

- platform: group
  name: Ground Floor Lights
  entities:
    - light.hallway_lights
    - light.dining_room_lights
    - light.kitchen_lights
    - light.toilet
    - light.living_room_lights

- platform: group
  name: Dining Room Lights
  entities:
    - light.dining_room_ceiling

- platform: group
  name: Living Room Lights
  unique_id: living_room_lights
  entities:
    - light.living_room_ceiling

- platform: group
  name: Walk-in Wardrobe Lights
  entities:
    - light.walk_in_wardrobe_ceiling

- platform: group
  name: Bedroom lights
  entities:
    - light.bedside_lamp_left
    - light.bedside_lamp_right
    - light.corner_lamp

- platform: group
  name: Bathroom Lights
  entities:
    - light.bathroom_ceiling

- platform: group
  name: Hallway Lights
  unique_id: hallway_lights
  entities:
    - light.entrance_hallway_1
    # - light.entrance_hallway_2
    # - light.entrance_hallway_3

- platform: group
  name: Staircase lights
  entities:
    - light.staircase_first_floor_hallway

- platform: group
  name: Kitchen Spots
  entities:
    - light.kitchen_spot_lower_left
    - light.kitchen_spot_lower_right
    - light.kitchen_spot_upper_left
    - light.kitchen_spot_upper_right

- platform: group
  name: Toilet Lights
  entities:
    - light.toilet

- platform: template
  lights:
    kitchen_cabinet:
      friendly_name: "Kitchen Cabinet"
      unique_id: "kitchen_cabinet"
      value_template: "{{ is_state('switch.smart_plug_cabinet', 'on') }}"
      turn_on:
        service: switch.turn_on
        entity_id: switch.smart_plug_cabinet
      turn_off:
        service: switch.turn_off
        entity_id: switch.smart_plug_cabinet
      icon_template: >-
        {% if is_state('switch.smart_plug_cabinet', 'on') %}
          mdi:lightbulb-on
        {% else %}
          mdi:lightbulb-off
        {% endif %}

- platform: group
  name: Kitchen Lights
  entities:
    # - light.kitchen_bench_upper_strip
    # - light.kitchen_bench_lower_strip
    - light.kitchen_spots
    # - light.table_lamp
    # - light.kitchen_cabinet
    # - light.kitchen_cabinet_strips

- platform: group
  name: Office Lights
  entities:
    - light.office_ceiling

- platform: group
  name: Guest Room Lights
  entities:
    - light.guest_room_ceiling

# - platform: template
#   lights:
#     laundry_lights:
#       friendly_name: "Laundry Lights"
#       unique_id: "laundry_lights"
#       state: >
#         {{ expand([
#             'light.laundry_left',
#             'light.laundry_middle',
#             'light.laundry_right'
#           ])
#           | selectattr('state','eq','on')
#           | list
#           | length > 0
#         }}
#       turn_on:
#         service: homeassistant.turn_on
#         target:
#           entity_id:
#             - light.laundry_left
#             - light.laundry_middle
#             - light.laundry_right
#       turn_off:
#         service: homeassistant.turn_off
#         target:
#           entity_id:
#             - light.laundry_left
#             - light.laundry_middle
#             - light.laundry_right
#       icon: mdi:lampt

- platform: group
  name: Gym Lights
  entities:
    - light.gym_ceiling

- platform: group
  name: Laundry Lights
  entities:
    - light.laundry_left
    - light.laundry_middle
    - light.laundry_right

