---
- platform: rest
  name: liam_cgm
  resource: !secret cgm_json_url
  value_template: >
    sgv:{{value_json[0].sgv}}, trend:{{value_json[0].trend}}, direction:{{value_json[0].direction}}, time:{{ ( (as_timestamp(now()) - as_timestamp(value_json[0].dateString) ) / 60) | round(0) }}

# - platform: github
#   access_token: !secret github_access_token
#   repositories:
#     - path: "liamwh/home-assistant-config"
#     - path: "liamwh/liamwh.com"

# Average out BG over 90 days (aka eAG value)
- platform: average
  name: "Glucose Avg 90d"
  duration:
    days: 90
  entities:
    - sensor.dexcom_liamwoodleigh_glucose_value

- platform: average
  name: "Glucose Avg 30d"
  duration:
    days: 30
  entities:
    - sensor.dexcom_liamwoodleigh_glucose_value

- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"

- platform: afvalbeheer
  wastecollector: mijnafvalwijzer
  resources:
    - restafval
    - papier
  postcode: !secret home_postcode
  streetnumber: !secret home_number
  upcomingsensor: 1

- platform: afvalwijzer
  provider: mijnafvalwijzer        # (required, default = mijnafvalwijzer) choose the provider for your community.
  postal_code: !secret home_postcode              # (required, default = '')
  street_number: !secret home_number                 # (required, default = '')
  suffix: ''                       # (optional, default = '')
  username: ''                     # (optional, default = '')
  password: ''                     # (optional, default = '')
  exclude_pickup_today: true       # (optional, default = true) to take or not to take Today into account in the next pickup.
  date_isoformat: false            # (optional, default = false) show the date in full isoformat if desired. Example: "2024-01-14T08:40:33.993521"
  default_label: geen              # (optional, default = geen) label if no date found
  id: ''                           # (optional, default = '') use if you'd like to have multiple waste pickup locations in HASS
  exclude_list: ''                 # (optional, default = '') comma separated list of wast types (case ignored). F.e. "papier, gft, restafval, pmd, etc"

- platform: statistics
  name: Temperature Sensor Bathroom Humidity Stats
  entity_id: sensor.temperature_sensor_bathroom_humidity
  state_characteristic: mean
  sampling_size: 86400 # make sure all data points of the last 24hrs are included
  max_age: "24:00:00"

- platform: derivative
  source: sensor.temperature_sensor_bathroom_humidity
  name: Temperature Sensor Bathroom Humidity Derivative
  unit_time: min
  time_window: "00:10:00"

# - platform: buienradar
#   name: "Buienradar"
#   latitude: !secret latitude_home
#   longitude: !secret longitude_home
#   timeframe: 120
#   monitored_conditions:
#     - stationname
#     - barometerfc
#     - barometerfcname
#     - conditioncode
#     - condition
#     - conditiondetailed
#     - conditionexact
#     - symbol
#     - feeltemperature
#     - humidity
#     - temperature
#     - groundtemperature
#     - windspeed
#     - windforce
#     - winddirection
#     - windazimuth
#     - pressure
#     - visibility
#     - windgust
#     - precipitation
#     - irradiance
#     - precipitation_forecast_average
#     - precipitation_forecast_total
#     - rainlast24hour
#     - rainlasthour

- platform: cryptoinfo
  cryptocurrency_name: "Cardano"
  currency_name: "usd"
  update_frequency: 10

- platform: cryptoinfo
  cryptocurrency_name: "Ethereum"
  currency_name: "usd"
  update_frequency: 10
