---
- platform: template
  switches:
    vacuum_mode:
      value_template: >
        {{ is_state("vacuum.xiaomi_vacuum_cleaner", "cleaning")}}
      turn_on:
        service: vacuum.start
        entity_id: vacuum.xiaomi_vacuum_cleaner
      turn_off:
        service: vacuum.return_to_base
        entity_id: vacuum.xiaomi_vacuum_cleaner
