blueprint:
  name: Motion-activated Light with Ambient Lux Check
  description: >
    Turn on a light when motion is detected - but only if ambient
    illuminance is below your configured threshold.
  domain: automation
  source_url: https://github.com/your-repo/blueprints/motion_light_lux.yaml

  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    light_sensor:
      name: Illuminance Sensor
      description: Sensor measuring ambient light (lux)
      selector:
        entity:
          domain: sensor
          device_class: illuminance

    illuminance_threshold:
      name: Lux Threshold
      description: >
        Maximum lux at which the light will turn on.
        If the reading is below this number, the light can switch on.
      default: 50
      selector:
        number:
          min: 0
          max: 10000
          unit_of_measurement: lx

    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light

    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input motion_entity
    from: "off"
    to: "on"

condition:
  - condition: numeric_state
    entity_id: !input light_sensor
    below: !input illuminance_threshold
  - condition: state
    entity_id: input_boolean.automatic_lights
    state: "on"


action:
  - service: light.turn_on
    target: !input light_target

  - wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"

  - delay: !input no_motion_wait

  - service: light.turn_off
    target: !input light_target